
language: python
python:
 - "3.5"
 - "3.6"
 - "nightly"

before_install:
 - "pip install mypy pipenv"
 - "pipenv install --dev"

install:
 - "make build"

script:
 - "python3 -c 'import aw_client'"
 - "mypy aw_client; echo 'Not a failing step'"

